<?php
/**
 * TL_ROOT/system/modules/conditionalforms/languages/hu/modules.php 
 * 
 * Contao extension: conditionalforms 1.0.0 stable 
 * Hungarian translation file 
 * 
 * Copyright : © 2008-2009 Andreas Schempp 
 * License   : LGPL 
 * Author    : Andreas Schempp (andreas.schempp), http://www.iserv.ch/ 
 * Translator: Gergő Nyiri (gremovan) 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['MOD']['conditionalforms']['0'] = "Feltételes formák";
 
?>
