<?php
/**
 * TL_ROOT/system/modules/conditionalforms/languages/hu/tl_form_field.php 
 * 
 * Contao extension: conditionalforms 1.0.0 stable 
 * Hungarian translation file 
 * 
 * Copyright : © 2008-2009 Andreas Schempp 
 * License   : LGPL 
 * Author    : Andreas Schempp (andreas.schempp), http://www.iserv.ch/ 
 * Translator: Gergő Nyiri (gremovan) 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_form_field']['conditionType']['0'] = "Mező típus";
$GLOBALS['TL_LANG']['tl_form_field']['conditionType']['1'] = "Több űrlapmező megjelenítése/elrejtése, melyek a <em>Csoport start</em> és <em>Csoport stop</em> elemek között vannak";
$GLOBALS['TL_LANG']['tl_form_field']['start']['0'] = "Csoport start";
$GLOBALS['TL_LANG']['tl_form_field']['start']['1'] = "Jelzi az elejét egy mező csoportnak.";
$GLOBALS['TL_LANG']['tl_form_field']['stop']['0'] = "Csoport stop";
$GLOBALS['TL_LANG']['tl_form_field']['stop']['1'] = "Jelzi a végét egy mező csoportnak.";
 
?>
